version: '3.6'
services:

  viewer:
    image: ohif/viewer:v3.7.1.10058
    container_name: viewer
    depends_on:
      - orthanc
    restart: always
    ports:
      - '80:80'
    networks:
      - frontend
      - backend
    volumes:
      # Nginx as a reversed proxy for orthanc and the viewer
      - ${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf:ro
      # OHIF Viewer configuration to reach DICOMWeb endpoints
      - ${VIEWER_CONFIG}:/usr/share/nginx/html/app-config.js:ro

  orthanc:
    image: osimis/orthanc:20.2.0
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      # configuration file
      - ${ORTHANC_CONFIG}:/etc/orthanc/orthanc.json:ro
      # storage volume for raw dicoms
      - ${ORTHANC_DB_MNT}:/var/lib/orthanc/db
    environment:
      # DICOMWeb Plugin
      - DW_ENABLED=true
      # Postgres Plugin
      - PG_ENABLED=true
    command: /etc/orthanc/orthanc.json

  postgres:
    image: postgres:12.1
    container_name: postgres
    networks:
      - backend
    volumes:
      - ${POSTGRES_DATA_MNT}:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=orthanc

networks:
  frontend:
  backend: